sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mehedimazumder/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehedimazumder/docker-react npm run test
