name: CI

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mehedimazumder/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true mehedimazumder/docker-react npm run test
